#setup-app.yml
---
  - hosts: webservers
    become: true
    tasks:
      - name: Upload_application_file
        copy:
          src: index.php
          dest: /var/www/html
          mode: 0755

      - name: Configure php.ini
        lineinfile:
          path: /etc/php.ini
          regexp: ^short_open_tag
          line: 'short_open_tag=On'

      - name: restart apache
        service: name=httpd state=restarted

      - name: This command will create a file called nope.txt
        ansible.builtin.shell:
          cmd: touch nope.txt
